import Head from "next/head";
import {
  Navbar,
  Products,
  Features,
  Pricing,
  Contacts,
  Footer,
} from "../components";
export default function Home() {
  return (
    <>
      <Head>
        <title>Lachin Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <Features />
        <Pricing />
        <Products />
        <Contacts />

        <Footer />
      </main>
    </>
  );
}
