import Head from "next/head";
import {
  Navbar,
  Products,
  Features,
  Pricing,
  Contacts,
  Footer,
} from "../components";
export default function Home() {
  return (
    <>
      <Head>
        <title>Lachin Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700;800&display=swap');
        </style>
      </Head>

      <main>
        <Navbar />

        <Features />

        <Footer />
      </main>
    </>
  );
}
